version: '3.8'

services:
  web:
    image: flask_docker
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - '.:/app'

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - '5050:80'
    depends_on:
      - db
volumes:
  pgdata:
